---

- name: "shell: login into ECR registry"
  shell: >
    $(aws ecr get-login --no-include-email --region {{ region }})
  tags:
    - prep

- name: "shell: tag and push images to ECR repositories"
  shell: >
   docker tag {{ item.0.key }}:{{ item.1 }} {{ item.0.value }}:{{ item.1 }} && \
   docker push {{ item.0.value }}:{{ item.1 }}
  with_together:
    - "{{ ecr_repositories|dict2items | product(app_versions)|list }}"
  tags:
    - prep

# - name: "debug: tag and push images to ECR repositories"
#   debug: msg="{{ item.0.key }} {{ item.0.value }}:{{ item.1 }}"
#   with_together:
#     - "{{ ecr_repositories|dict2items | product(app_versions)|list }}"
#   tags:
#     - prep
