---

- block:

  - name: "set_fact: save 'terraform.tfvars' location"
    set_fact:
      tfvars: "../terraform/terraform.tfvars"

  - name: get hosted_zone value
    shell: |
      egrep -i "^hosted_zone.*=.*" {{ tfvars }} | awk -F '"' '{print $2}'
    register:
      hosted_zone_output

  - name: "set_fact: save pretty 'hosted_zone' value"
    set_fact:
      hosted_zone: "{{ hosted_zone_output.stdout }}"

  - name: "debug: check 'hosted_zone' variable"
    debug: msg="{{ hosted_zone }}"

  - name: "template: template 'ssl_config' file for ssl certs generation"
    template:
      src: "ssl_config.cfg.j2"
      dest: "ssl_config.cfg"
      force: true

  - name: "shell: generate self-signed SSL"
    shell: |
       openssl req -x509 -config ssl_config.cfg \
                         -extensions req_ext \
                         -nodes \
                         -days 3650 \
                         -newkey rsa:2048 \
                         -sha256 \
                         -keyout {{ hosted_zone }}_wildcard.key \
                         -out {{ hosted_zone }}_wildcard.crt


  - name: "shell: upload certificate to AWS ACM"
    shell: |
      aws acm import-certificate \
              --certificate file://{{ hosted_zone }}_wildcard.crt \
              --private-key file://{{ hosted_zone }}_wildcard.key

  tags:
    - prep_ssl
