---
- hosts: localhost
  connection: local

  vars:
    readiness:
      - "available"

  tasks:

    - name: "shell: ensure efs mount-point(s) is(are) available"
      shell: >
        aws efs describe-mount-targets \
                --file-system-id {{ efs_id }} \
                --query 'MountTargets[*].LifeCycleState' \
                --output text | tr "\t" "\n"
      register: lifecycle_state
      until: lifecycle_state.stdout_lines | unique == readiness
      retries: 30
      delay: 10
