---
- hosts: localhost

  tasks:

    - name: "set_fact: save 'ansible_vars_path'"
      set_fact:
        ansible_vars_path: "../ansible/group_vars"
        terraform_vars_path: "../terraform"

    - name: "shell: form outputs file and save tfvars for Ansible re-use"
      shell: |
        terraform output -state "{{ tfstate | default('terraform.tfstate') }}" | sed "s/[ ]*=[ ]*/: /g" > "{{ ansible_vars_path }}/terraform_outputs.yaml"
        cat terraform.tfvars | sed "s/[ ]*=[ ]*/: /g" > "{{ ansible_vars_path }}/terraform_tfvars.yaml"
      args:
        chdir: "{{ terraform_vars_path }}"
