version: '2'

services:
  fpm:
    image: ${ECR_WORDPRESS_URL}:${DEPLOY_VERSION}
    container_name: fpm
    volumes:
      - /var/www/html
      - ${WP_UPLOADS}:/var/www/html/web/app/uploads
    environment:
      DB_NAME: ${RDS_DB_NAME}
      DB_USER: ${RDS_USERNAME}
      DB_PASSWORD: ${RDS_PASSWORD}
      DB_HOST: ${RDS_ENDPOINT}
      WP_HOME: ${APP_SCHEMA}://${ALIAS_RECORD}
      WP_SITEURL: ${APP_SCHEMA}://${ALIAS_RECORD}/wp
      WP_ENV: ${WP_ENV}
      # wp settings
      SITE_TITLE: ${SITE_TITLE}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
  nginx:
    image: ${ECR_NGINX_URL}:${DEPLOY_VERSION}
    container_name: nginx
    links:
      - fpm:fpm
    volumes_from:
      - fpm
    ports:
      - "${APP_FRONTEND_PORT}:${APP_FRONTEND_PORT}"
    environment:
      ALLOW_INSTALL: "yes"
